install.packages("GGally")

library(shiny)
library(ggplot2)
library(DT)       
library(corrplot)  
library(GGally)     
# Veri setini yükleme

data <- read_excel("desktop/r project/overview.xlsx")

## Veri Düzenleme. 

# distance değişkeni chr olarak gelmiş onu num olarak düzeltelim
data$Distance <- as.numeric(data$Distance)
# 'Battery State of Charge (Start)' ve 'Battery State of Charge (End)' sütunlarını çıkarma
data <- select(data, -c('Battery State of Charge (Start)', 'Battery State of Charge (End)'))
# Sadece sayısal değişkenleri içeren bir veri çerçevesi
numeric_data <- data %>% select_if(is.numeric)


# UI tanımı
ui <- fluidPage(
  # Başlık
  titlePanel("Dış Etkenlerin Elektrikli Araç Bataryasına Etkisi"),
  
  # Menü seçenekleri
  navbarPage("Menü", id="navbar",
             tabPanel("Dataset",
                      fluidRow(
                        column(11, DTOutput("table_head"))
                      )
             ),
             tabPanel("Dataset Info",
                      fluidRow(
                        column(12,
                               verbatimTextOutput("dataset_info")
                        ),
                        column(12,
                               HTML('<a href="https://www.kaggle.com/datasets/atechnohazard/battery-and-heating-data-in-real-driving-cycles" target="_blank">Source of the Dataset</a>')
                        )
                      )
             ),
             
             tabPanel("Histogram Plotları",
                      fluidRow(
                        selectInput("var_select", "Değişken Seçiniz:", choices = names(numeric_data)),
                        plotOutput("histogramPlot")
                      )
             ),
             tabPanel("Korelasyon Matrisi",
                      plotOutput("correlationMatrix")
             ),
             tabPanel("Lineer Regresyon - [Sıcaklık-Kullanım]",
                      fluidRow(
                        plotOutput("linearRegSimple"),
                        column(12, verbatimTextOutput("regressionComment"))
                      )
                      
             ),
             tabPanel("Lineer Regresyon - [Tüm Değişkenler]",
                      fluidRow(
                        DTOutput("linearRegMultiple"),
                        
                        column(12, verbatimTextOutput("modelSummary"))
                      )
             ),
             tabPanel("Hazırlayan",
                      fluidRow(
                        column(12, wellPanel(
                          h4("Ekin Emre Atasoy"),
                          h4("2023000098")
                        )),
                        column(12, verbatimTextOutput("conclusionText"))
                      )
             )
  )
)


### Server Tanımı

# Server mantığı
server <- function(input, output) {
  # Dataset Göster
  output$table_head <- renderDT({
    datatable(data, options = list(pageLength = 25))
  })
  
  # Dataset Info
  output$dataset_info <- renderText({
    "Originally sourced from: IEEE DataPort\n\nHigh-voltage batteries in battery electric vehicles face significant load fluctuations due to driving behavior.
      This dynamic performance of the powertrain is contrasted by the almost constant load of the auxiliary consumers. 
      The highest auxiliary consumption is generated by the heating and air conditioning system, which decreases the vehicle's range significantly. 
      72 real driving trips with a BMW i3 (60 Ah) were recorded, serving for model validation of a full vehicle model consisting of the powertrain and the heating circuit.
      \n\nEach trip contains:\n\n- Environmental data (temperature, elevation, etc.)\n- Vehicle data (speed, throttle, etc.)\n- Battery data (voltage, current, temperature, SoC)\n- Heating circuit data (indoor temperature, heating power, etc.)
      \nThe measurement data is in CSV format to ensure easy use by various standard programs (Excel, Matlab) or own developed codes (Python).
      \n\nThe script 'readin.m' reads the csv files into MatLab as table and struct.\n\nThe data contains vehicle data, battery data and heating data.
      \nThe measurement data is divided into two categories. Category A was recorded in summer and does not contain all measured data due to trouble with the measurement system. 
      Category B was recorded in winter and is consistent."
  })
  # Histogram Plotları
  output$histogramPlot <- renderPlot({
    ggplot(data, aes_string(x = input$var_select)) +
      geom_histogram(bins = 30, fill = "blue", color = "black") +
      labs(title = paste(input$var_select, "Histogramı"))
  })
  
  # Korelasyon matrisi
  output$correlationMatrix <- renderPlot({
    correlation_matrix <- cor(numeric_data, use = "complete.obs")
    corrplot(correlation_matrix, method = "circle")
  })
  
  # Basit Lineer Regresyon Görselleştirme
  output$linearRegSimple <- renderPlot({
    ggplot(data, aes(x = Temperature, y = Lost)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE, color = "blue") +
      labs(title = "Basit Lineer Regresyon Modeli",
           x = "Temperature", y = "Lost")
  })
  
  # Basit Lineer Regresyon Yorumu
  output$regressionComment <- renderText({
    "Grafikte gösterilen basit lineer regresyon modeline göre, sıcaklık ile Kaybedilen Batarya yüzdesi arasında çok hafif negatif bir ilişki bulunmaktadır.
      Ancak, mavi çizginin yatay olması ve veri noktalarının geniş bir alana yayılması, bu iki değişken arasında güçlü bir ilişki olmadığına işaret etmektedir.
      Bu, sıcaklığın Kaybedilen Batarya yüzdesi değerlerini anlamlı bir şekilde tahmin etmede önemli bir faktör olmayabileceğini göstermektedir."
  })
  
  library(DT)
  # Çoklu Lineer Regresyon Modeli Katsayıları
  output$linearRegMultiple <- renderDT({
    numeric_data <- data %>% select_if(is.numeric)
    model_all <- lm(Lost ~ ., data = numeric_data)
    coef_data <- as.data.frame(coef(summary(model_all)))
    datatable(coef_data, options = list(pageLength = 10, autoWidth = TRUE))
  })
  output$modelSummary <- renderText({
    "Modelde 'Distance' ve 'Duration' değişkenleri istatistiksel olarak anlamlı bulunmuştur ve negatif bir etkiye sahiptir, bu da mesafe ve sürenin artmasıyla 'Lost' değerinin azaldığını gösterir.
      Ancak, bu sonuçlar pratikte beklenen bir durum olmayabilir ve verilerdeki gürültüden veya modelin overfitting olmasından kaynaklanıyor olabilir.
      Diğer tüm değişkenler ('Battery_Temperature_Start', 'Battery_Temperature_End', 'Cabin_Temperature', 'Temperature') modelde istatistiksel olarak anlamlı bulunmamıştır."
  })
  
  output$conclusionText <- renderText({
    "Sonuç olarak, istenilen sonuçlar elde edilmemiş olmasına rağmen, daha fazla veriye ihtiyaç duyulduğu ve derinlemesine bir araştırma yapılması gerektiği anlaşılmıştır.\nShiny uygulaması, bu süreçte veri analizi ve modelleme için kullanılmıştır."
  })
  
  
  
  
}

shinyApp(ui = ui, server = server)


